FROM golang:alpine3.20 AS builder

ENV GO111MODULE=on \
    CGO_ENABLED=1

WORKDIR /src

COPY ./src /src
RUN go mod download && go mod verify

COPY . .

RUN go build -v -o /out/build .

FROM scratch
COPY --chown=0:0 --from=builder /out/build ./
ENTRYPOINT [ "./build" ]